/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: Reed Fansler (https://sketchfab.com/reedfansler)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/arrow-gray-53036ecd0b5f494fac6cc7d7c86b41a6
Title: Arrow Gray
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Arrow(props) {
  const { nodes, materials } = useGLTF('/models/arrow/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.blinn2SG} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/arrow/scene.gltf')
